---
- name: GIT PULL USER MY CONFIG REPO
  become: 'no'
  git:
    repo: 'https://github.com/wojciechGaudnik/my-config.git'
    dest: '~/.my-config'
    force: no
    version: master

- name: GIT PULL ROOT MY CONFIG REPO
  become: 'yes'
  git:
    repo: 'https://github.com/wojciechGaudnik/my-config.git'
    dest: '~/.my-config'
    force: no
    version: master
