require "wgaudnik.options"
require "wgaudnik.keymaps"
require "wgaudnik.plugins"
require "wgaudnik.colors"
require "wgaudnik.autocompletion"
require "wgaudnik.lsp"
require "wgaudnik.telescope"
require "wgaudnik.treesitter"
require "wgaudnik.colorizer"

