---
- name: INSTALL
  become: 'yes'
  apt:
    name: 'git'
    state: latest


- name: GIT USER EMAIL AND NAME
  become: 'no'
  git_config:
    name: '{{ item.name }}'
    scope: '{{ item.scope }}'
    value: '{{ item.value }}'
  with_items:
    - {name: 'user.email', scope: 'global', value: 'wojciech.gaudnik@gmail.com'}
    - {name: 'user.name', scope: 'global', value: 'Wojciech Gaudnik'}


- name: GIT ROOT EMAIL AND NAME
  become: 'yes'
  git_config:
    name: '{{ item.name }}'
    scope: '{{ item.scope }}'
    value: '{{ item.value }}'
  with_items:
    - {name: 'user.email', scope: 'global', value: 'wojciech.gaudnik@gmail.com'}
    - {name: 'user.name', scope: 'global', value: 'Wojciech Gaudnik'}
