- name: SETUP DEFAULT SHELL
  become: 'yes'
  user:
    name: 'root'
    shell: /usr/bin/zsh
- name: LINK FILES
  become: 'yes'
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
    mode='{{ item.mode }}'
  with_items:
    - {src: '~/.my-config/CMD/bash/resetNET.sh', dest: '/usr/bin/resetNET.sh', state: 'link', force: 'yes', mode: '0700'}
    - {src: '~/.my-config/CMD/bash/resetNFS.sh', dest: '/usr/bin/resetNFS.sh', state: 'link', force: 'yes', mode: '0700'}
    - {src: '~/.my-config/CMD/bash/resetUSB.sh', dest: '/usr/bin/resetUSB.sh', state: 'link', force: 'yes', mode: '0700'}
    - {src: '~/.my-config/CMD/bash/testBIOSorURFI.sh', dest: '/usr/bin/testBIOSorURFI.sh', state: 'link', force: 'yes', mode: '0700'}
    - {src: '~/.my-config/CMD/bash/testTrueColorConsole.sh', dest: '/usr/bin/testTrueColorConsole.sh', state: 'link', force: 'yes', mode: '0700'}
    - {src: '~/.my-config/CMD/config/etc/environment', dest: '/etc/', state: 'link', force: 'yes', mode: '0700'}
- name: COPY FILES
  become: 'yes'
  copy:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    remote_src='{{ item.remote_src }}'
    mode='{{ item.mode }}'
  with_items:
    - {src: '~/.my-config/CMD/config/mc/mc.default.keymap', dest: '/etc/mc/mc.default.keymap', remote_src: 'yes', mode: '0644'}
- name : MC ROOT RED INDICATOR
  become: yes
  lineinfile:
    path: '~/.config/mc/ini'
    regex: '^skin='
    line: "skin=modarin256root-defbg"
    backrefs: yes
