- git_config:
    name: '{{ item.name }}'
    scope: '{{ item.scope }}'
    value: '{{ item.value }}'
  with_items:
    - {name: 'user.email', scope: 'global', value: 'wojciech.gaudnik@gmail.com'}
    - {name: 'user.name', scope: 'global', value: 'Wojciech Gaudnik'}
