- name: APT INSTALL
  become: 'yes'
  register: reg_vnstat_install
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'vnstat'}
- name: VNSTAT SETUP
  become: 'yes'
  when: reg_vnstat_install.changed
  copy:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    remote_src='{{ item.remote_src }}'
    mode='{{ item.mode }}'
  with_items:
    - {src: '~/.my-config/CMD/config/vnstat/etc/vnstat.conf', dest: '/etc/vnstat.conf', remote_src: 'yes', mode: '0644' }
    - {src: '~/.my-config/CMD/config/vnstat/var/lib/vnstat/vnstat.db', dest: '/var/lib/vnstat/vnstat.db', remote_src: 'yes', mode: '0644' }
