- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'net-tools'}
    - {source: 'wakeonlan'}
    - {source: 'ethtool'}
    - {source: 'speedtest-cli'}
    - {source: 'openvpn'}
    - {source: 'whois'}
    - {source: 'nfs-common'}
- name: VNSTAT
  import_tasks: vnstat.yml
- name: WAKE ON LAN
  import_tasks: wake_on_lan.yml
- name: HOSTS ETC
  import_tasks: hosts_etc.yml
