- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'net-tools'}
    - {source: 'wakeonlan'}
    - {source: 'speedtest-cli'}
    - {source: 'openvpn'}
    - {source: 'lynis'}
    - {source: 'nmap'}
    - {source: 'whois'}
    - {source: 'tshark'}
# - name: ADDITIONAL
  # import_tasks: additionals.yml
