- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'net-tools'}
    - {source: 'wakeonlan'}
    - {source: 'ethtool'}
    - {source: 'speedtest-cli'}
    - {source: 'openvpn'}
    - {source: 'whois'}
- name: ADDITIONAL
  import_tasks: additionals.yml
