- name: TEST WAKE ON LAN
  become: 'yes'
  vars:
    ip_addr: "{{ ansible_default_ipv4.address }}"
    all_inter: "{{ ansible_facts | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value') | list }}"
    inter: "{{ all_inter | selectattr('ipv4.address', 'equalto', ip_addr) | first }}"
  register: reg_wake_on_lan_test
  shell: 'cat /sys/class/net/{{ inter.device }}/device/power/wakeup'
  changed_when: false
  when: inventory_hostname in groups['WAKE_ON_LAN_HOSTS']
- name: SET WAKE ON LAN
  become: 'yes'
  vars:
    ip_addr: "{{ ansible_default_ipv4.address }}"
    all_inter: "{{ ansible_facts | dict2items | selectattr('value.ipv4', 'defined') | map(attribute='value') | list }}"
    inter: "{{ all_inter | selectattr('ipv4.address', 'equalto', ip_addr) | first }}"
  shell: "ethtool --change {{ inter.device }} wol g"
  when: reg_wake_on_lan_test.stdout is defined and reg_wake_on_lan_test.stdout == 'disabled'
