- name: CHROME ADD KEY
  become: 'yes'
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present
- name: ADD ADDITIONAL REPOTS
  become: 'yes'
  apt_repository:
    repo: '{{ item.repo }}'
    state: '{{ item.state }}'
  with_items:
    - {repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main', state: 'present' }
    - {repo: 'ppa:solaar-unifying/ppa', state: 'present' }
    - {repo: 'ppa:openrazer/stable', state: 'present' }
    - {repo: 'ppa:polychromatic/stable', state: 'present' }
    - {repo: 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main', state: 'present' }
- name: APT UPDATE AND UPGRADE
  become: 'yes'
  apt:
    update_cache: 'yes'
    upgrade: 'yes'
    force_apt_get: 'yes'
    cache_valid_time: 3600
    autoremove: 'yes'
