- name: CHROME ADD KEY
  become: 'yes'
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present
- name: CHROME ADD REPO
  become: 'yes'
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
- name: APT UPDATE AND UPGRADE
  become: 'yes'
  apt:
    update_cache: 'yes'
    upgrade: 'yes'
    force_apt_get: 'yes'
    cache_valid_time: 3600
    autoremove: 'yes'
