- name: ADDITIONAL
  import_tasks: additionals.yml
- name: APT INSTALL
  become: 'yes'
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'tilix'}
    - {source: 'dconf-cli'}
    - {source: 'google-chrome-stable'}
    - {source: 'ttf-mscorefonts-installer'}
