- name: ADDITIONAL
  import_tasks: additionals.yml
- name: APT INSTALL
  become: 'yes'
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'ttf-mscorefonts-installer'}
    - {source: 'tilix'}
    - {source: 'dconf-cli'}
    - {source: 'conky-all'}
    - {source: 'google-chrome-stable'}
    - {source: 'solaar'}
    - {source: 'thunderbird'}
    - {source: 'thunderbird-locale-en'}
    - {source: 'thunderbird-locale-en-us'}
    - {source: 'libreoffice-kde5'}
    - {source: 'openrazer-meta'}
    - {source: 'polychromatic'}

