- name: APT INSTALL
  become: 'yes'
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'tilix'}
    - {source: 'dconf-cli'}
- name: CHROME INSTALL
  import_tasks: chrome_install.yml
