---
- name: APT INSTALL
  become: 'yes'
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'thunderbird'}
    - {source: 'thunderbird-locale-en'}
    - {source: 'thunderbird-locale-en-us'}
    - {source: 'libreoffice-kde5'}
    - {source: 'libreoffice-java-common'}
    - {source: 'latte-dock'}
    - {source: 'kcolorchooser'}
    - {source: 'timeshift'}
    - {source: 'filelight'}
    - {source: 'synaptic'}
    - {source: 'wine'}
    - {source: 'playonlinux'}
    - {source: 'handbrake'}
    - {source: 'simplescreenrecorder'}
    - {source: 'ffmpeg'}
    - {source: 'obs-studio'}
    - {source: 'vlc'}
    - {source: 'gimp'}
    - {source: 'qbittorrent'}
    - {source: 'wireshark'}
    - {source: 'ksysguard'}
    # - {source: 'slack-desktop'}
    # - {source: 'discord'}
    # - {source: 'aptik'}

