- name: APT INSTALL
  become: 'yes'
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'john'}
    - {source: 'lynis'}
    - {source: 'nmap'}
    - {source: 'tshark'}
    - {source: 'arp-scan'}
    - {source: 'masscan'}
    # - {source: 'feroxbuster'}
    # - {source: 'ffuf'}
    # - {source: 'dirb'}
    # - {source: 'gobuster'}
