---
- name: ZSH APT INSTALL
  become: 'yes'
  apt:
    name: "zsh"
    state: latest

- name: ZSH USER SETUP DEFAULT SHELL
  become: 'yes'
  user:
    name: 'bq666'
    shell: /usr/bin/zsh

- name: ZSH ROOT SETUP DEFAULT SHELL
  become: 'yes'
  user:
    name: 'root'
    shell: /usr/bin/zsh

- name: ZSH USER GIT PULL REPOS
  become: 'no'
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    force: '{{ item.force }}'
    version: master
  with_items:
    - {repo: 'https://github.com/robbyrussell/oh-my-zsh', dest: '~/.oh-my-zsh', force: 'yes'}
    - {repo: 'https://github.com/romkatv/powerlevel10k.git', dest: '~/.oh-my-zsh/custom/themes/powerlevel10k', force: 'yes'}
    - {repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions', force: 'yes'}
    - {repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting', force: 'yes'}

- name: ZSH ROOT GIT PULL REPOS
  become: 'yes'
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    force: '{{ item.force }}'
    version: master
  with_items:
    - {repo: 'https://github.com/robbyrussell/oh-my-zsh', dest: '~/.oh-my-zsh', force: 'yes'}
    - {repo: 'https://github.com/romkatv/powerlevel10k.git', dest: '~/.oh-my-zsh/custom/themes/powerlevel10k', force: 'yes'}
    - {repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions', force: 'yes'}
    - {repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting', force: 'yes'}

- name: ZSH USER LINK FILES
  become: 'no'
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
  with_items:
    - {src: '~/.my-config/CMD/config/.zshrc', dest: '~/.zshrc', state: 'link', force: 'yes'}
    - {src: '~/.my-config/CMD/config/.p10k.zsh', dest: '~/.p10k.zsh', state: 'link', force: 'yes'}
    - {src: '~/.my-config/CMD/config/.usefullCommands.txt', dest: '~/.usefullCommands.txt', state: 'link', force: 'yes'}

- name: ZSH ROOT LINK FILES
  become: 'yes'
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
  with_items:
    - {src: '~/.my-config/CMD/config/.zshrc', dest: '~/.zshrc', state: 'link', force: 'yes'}
    - {src: '~/.my-config/CMD/config/.p10k.zsh', dest: '~/.p10k.zsh', state: 'link', force: 'yes'}
    - {src: '~/.my-config/CMD/config/.usefullCommands.txt', dest: '~/.usefullCommands.txt', state: 'link', force: 'yes'}
