- name: WALLPAPERS DIRECTORY CREATE
  become: 'yes'
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
  with_items:
    - {path: '/usr/share/wallpapers/MyWallpapers', state: 'directory'}
- name: WALLPAPERS COPY
  become: 'yes'
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    remote_src: '{{ item.remote_src }}'
  with_items:
    - {src: '~/.my-config/KDE/.local/share/wallpapers/left.png', dest: '/usr/share/wallpapers/MyWallpapers/', remote_src: 'yes'}
    - {src: '~/.my-config/KDE/.local/share/wallpapers/center.jpg', dest: '/usr/share/wallpapers/MyWallpapers/', remote_src: 'yes'}
    - {src: '~/.my-config/KDE/.local/share/wallpapers/right.jpg', dest: '/usr/share/wallpapers/MyWallpapers/', remote_src: 'yes'}
    - {src: '~/.my-config/KDE/.local/share/wallpapers/top.jpg', dest: '/usr/share/wallpapers/MyWallpapers/', remote_src: 'yes'}
    - {src: '~/.my-config/KDE/.local/share/wallpapers/login.jpg', dest: '/usr/share/wallpapers/MyWallpapers/', remote_src: 'yes'}
