- name: SET NVME
  become: 'yes'
  when: reg_nvme_cli_install.changed
  file:
    path: '{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - {path: '/usr/sbin/nvme', mode: '4555'}
    - {path: '/sbin/nvme', mode: '4555'}
- name: LM_SENSORS
  become: 'yes'
  when: reg_lm_sensors_install.changed
  expect:
    timeout: 60
    echo: yes
    command: /sbin/sensors-detect
    responses:
      'Do you want to add these lines automatically to /etc/modules? (yes/NO)': 'yes'
      .*(YES|yes).*: 'Yes'
      .*ENTER.*: ''
