- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'iftop'}
    - {source: 'hwinfo'}
    - {source: 'smem'}
    - {source: 'glances'}
    - {source: 'iotop'}
    - {source: 'powertop'}
    - {source: 'sysbench'}
    - {source: 'inxi'}
    - {source: 'stress'}
    - {source: 'stress-ng'}
    - {source: 'glmark2'}
- name: NVME-CLI INSTALL
  become: 'yes'
  apt:
    name: 'nvme-cli'
    state: latest
  register: reg_nvme_cli_install
- name: APT LM_SENSORS INSTALL
  become: 'yes'
  apt:
    name: 'lm-sensors'
    state: latest
  register: reg_lm_sensors_install
- name: ADDITIONAL
  import_tasks: additionals.yml
