#!/bin/sh
echo "suspend custom modules works !!!">>/var/log/system_suspend_big.log
if [ $1 = 'pre' ]
then
  echo "we are suspending at $(date)...">>/var/log/system_suspend_big.log
  # modprobe -r atlantic
  echo "unload atlantic OK">>/var/log/system_suspend_big.log
elif [ ${1} = 'post' ]
then
  echo "..and we are back from $(date)">>/var/log/system_suspend_big.log
  # modprobe -i atlantic
  # echo "1">/sys/class/drm/card0/device/hwmon/hwmon5/pwm1_enable
  # wakeonlan $OLD_MAC
  echo "load atlantic OK">>/var/log/system_suspend_big.log
fi
