#!/bin/sh
echo "suspend custom modules works !!!">>/var/lib/systemd_suspend_big
if [ $1 = 'pre' ]
then
  echo "we are suspending at $(date)...">>/var/lib/systemd_suspend_big
  # modprobe -r atlantic
  echo "unload atlantic OK">>/var/lib/systemd_suspend_big
elif [ ${1} = 'post' ]
then
  echo "..and we are back from $(date)">>/var/lib/systemd_suspend_big
  # modprobe -i atlantic
  # echo "1">/sys/class/drm/card0/device/hwmon/hwmon5/pwm1_enable
  # wakeonlan $OLD_MAC
  echo "load atlantic OK">> /tmp/systemd_suspend_test
fi
