#!/bin/sh
echo "suspend custom modules works !!!">> /tmp/systemd_suspend_test
if [ $1 = 'pre' ]
then
  echo "we are suspending at $(date)...">> /tmp/systemd_suspend_test
  modprobe -r atlantic
  echo "unload atlantic OK">> /tmp/systemd_suspend_test
elif [ ${1} = 'post' ]
then
  echo "..and we are back from $(date)">> /tmp/systemd_suspend_test
  modprobe -i atlantic
  echo "1">/sys/class/drm/card0/device/hwmon/hwmon5/pwm1_enable
  wakeonlan $OLD_MAC
  echo "load atlantic OK">> /tmp/systemd_suspend_test
fi
