- name: NET
  import_tasks: net.yml
- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'radeontop'}

- name: CREATE DIR
  become: 'no'
  file:
    path='{{ item.path }}'
    state='{{ item.state }}'
    recurse='{{ item.recurse }}'
  with_items:
    - {path: '/mnt/NAS_Backups', state: 'directory', recurse: 'yes'}
    - {path: '/mnt/NAS_Important', state: 'directory', recurse: 'yes'}
    - {path: '/mnt/NAS_Plex', state: 'directory', recurse: 'yes'}
    - {path: '/mnt/NAS_Storage', state: 'directory', recurse: 'yes'}
    - {path: '/mnt/NAS_VirtualBox', state: 'directory', recurse: 'yes'}
    - {path: '/mnt/usb', state: 'directory', recurse: 'yes'}
