---
- name: APT INSTALL
  become: 'yes'
  apt:
    name: 'conky-all'
    state: latest

- name: CREATE DIRECTORY
  file:
    path: '~/.config/conky/'
    state: 'directory'

- name: LINK FILES
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
  with_items:
    - {src: '~/.my-config/KDE/.config/conky_LEN/conky-startup.sh', dest: '~/.config/autostart-scripts/conky-startup.sh', state: 'link', force: 'yes'}
    - {src: '~/.my-config/KDE/.config/conky_LEN/.conky.conf', dest: '~/.config/conky/.conky.conf', state: 'link', force: 'yes'}
    - {src: '~/.my-config/KDE/.config/conky_LEN/NetStatRead.py', dest: '~/.config/conky/NetStatRead.py', state: 'link', force: 'yes'}
