- name: APT UPDATE AND UPGRADE
  apt:
    update_cache: yes
    upgrade: 'yes'
    force_apt_get: yes
    cache_valid_time: 3600
    autoremove: yes
- name: APT INSTALL
  become: yes
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'git'}
    - {source: 'zsh'}
    - {source: 'wget'}
    - {source: 'curl'}
    - {source: 'ruby-full'}
    - {source: 'build-essential'}
    - {source: 'python3-distutils'}
    - {source: 'python3-pip'}
    - {source: 'thefuck'}
    - {source: 'autojump'}
    - {source: 'tmux'}
    - {source: 'screenfetch'}
    - {source: 'mc'}
    - {source: 'htop'}
    - {source: 'ripgrep'}
    - {source: 'ansible-lint'}
    - {source: 'cmake'}
