- name: APT UPDATE AND UPGRADE
  apt:
    update_cache: yes
    upgrade: 'yes'
    force_apt_get: yes
    cache_valid_time: 3600
    autoremove: yes
- name: APT INSTALL
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'git'}
    - {source: 'zsh'}
    - {source: 'wget'}
    - {source: 'curl'}
    - {source: 'ruby-full'}
    - {source: 'build-essential'}
    - {source: 'python3-distutils'}
    - {source: 'python3-pip'}
    - {source: 'thefuck'}
    - {source: 'autojump'}
    - {source: 'tmux'}
    - {source: 'screenfetch'}
    - {source: 'mc'}
    - {source: 'htop'}
    - {source: 'ripgrep'}
    - {source: 'ansible-lint'}
    - {source: 'cmake'}
- name: APT VIM INSTALL
  register: reg_vim_install
  apt:
    name: 'vim'
    state: latest
- name: LM_SENSORS APT INSTALL
  register: reg_lm_sensors_install
  apt:
    name: 'lm-sensors'
    state: latest
