---
#========================== confing =============================================================
- name: cmd
  hosts: ALL
  user: bq666
  tasks:
    - name: APT UPDATE AND UPGRADE
      become: yes
      apt:
        update_cache: yes
        upgrade: 'yes'
        force_apt_get: yes
        cache_valid_time: 3600
        autoremove: yes
    - name: APT INSTALL
      become: yes
      apt:
        name: "{{ item.source }}"
        state: latest
      with_items:
        - {source: 'git'}
        - {source: 'zsh'}
        - {source: 'wget'}
        - {source: 'curl'}
        - {source: 'ruby-full'}
        - {source: 'build-essential'}
        - {source: 'python3-distutils'}
        - {source: 'python3-pip'}
        - {source: 'thefuck'}
        - {source: 'autojump'}
        - {source: 'tmux'}
        - {source: 'screenfetch'}
        - {source: 'mc'}
        - {source: 'htop'}
        - {source: 'ripgrep'}
        - {source: 'ansible-lint'}
        - {source: 'cmake'}
    - name: APT VIM INSTALL
      become: yes
      register: reg_vim
      apt:
        name: 'vim'
        state: latest
    - name: PIP VIM-VINT INSTALL
      become: yes
      pip:
       name: vim-vint
       state: latest
    - name: LM_SENSORS APT INSTALL
      become: yes
      register: reg_lm_sensors
      apt:
        name: 'lm-sensors'
        state: latest
    - name: COLORLS GEM INSTALL
      become: yes
      gem:
        name: colorls
        user_install: no
        state: latest
    - name: VIVM INSTALL
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/thameera/vimv/master/vimv
        dest: /usr/local/bin/vimv
        mode: '0755'
    - name: MY CONFIG FOR ROOT
      become: yes
      tags:
        - mytest
      register: reg_my_config_root
      git:
        repo: 'https://github.com/wojciechGaudnik/my-config.git'
        dest: '~/.my-config'
        version: master
    - name: MY CONFIG FOR BQ666
      git:
        repo: 'https://github.com/wojciechGaudnik/my-config.git'
        dest: '~/.my-config'
        version: master
    - name: LM_SENSORS SETUP
      become: yes
      when: reg_lm_sensors.changed
      expect:
        timeout: 5
        echo: yes
        command: /sbin/sensors-detect
        responses:
          .*(YES|yes).*: "Yes"
          .*ENTER.*: ""
    - name: FONTS COPY
      become: yes
      register: reg_fontsHack
      copy:
        src: ~/.my-config/fonts_hack
        dest: /usr/share/fonts
        remote_src: yes
    - name: FONTS CONFIG
      when: reg_fontsHack.changed
      command:
        cmd: /bin/fc-cache -f
    - name: USB RESET COPY
      become: yes
      copy:
        src: ~/.my-config/usbreset.sh
        dest: /usr/bin/
        remote_src: yes
        mode: u+rwx,g-rwx,o-rwx
    - name: MC GLOBAL CONFIG
      become: yes
      copy:
        src: ~/.my-config/root/mc/mc.default.keymap
        dest: /etc/mc/
        remote_src: yes
        mode: u+rw,g+r,o+r
#========================== root ================================================================
#-------------------------- git -----------------------------------------------------------------
    - name: ROOT GIT REPOS
      become: yes
      tags:
        - mytest
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        force: "{{ item.force }}"
        version: master
      with_items:
        - {repo: 'https://github.com/robbyrussell/oh-my-zsh', dest: '~/.oh-my-zsh', force: yes}
        - {repo: 'https://github.com/romkatv/powerlevel10k.git', dest: '~/.oh-my-zsh/custom/themes/powerlevel10k', force: yes}
        - {repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions', force: yes}
        - {repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting', force: yes}
        - {repo: 'https://github.com/tmux-plugins/tpm', dest: '~/.tmux/plugins/tpm', force: yes}
#-------------------------- copy ----------------------------------------------------------------
    - name: ROOT CREATE DIR
      become: yes
      ansible.builtin.file:
        path="{{ item.path }}"
        state="{{ item.state }}"
        recurse="{{ item.recurse }}"
      with_items:
        - {path: '~/.config/mc', state: 'directory', recurse: 'yes'}
        - {path: '~/.config/htop', state: 'directory', recurse: 'yes'}
        - {path: '~/.vim/colors', state: 'directory', recurse: 'yes'}
        - {path: '~/.vim/undodir', state: 'directory', recurse: 'yes'}
        - {path: '~/.vim/spell', state: 'directory', recurse: 'yes'}
    - name: ROOT LINK FILES
      become: yes
      ansible.builtin.file:
        src="{{ item.src }}"
        dest="{{ item.dest }}"
        state="{{ item.state }}"
        force="{{ item.force }}"
      with_items:
        - {src: "~/.my-config/.zshrc", dest: "~/.zshrc", state: "link", force: yes}
        - {src: "~/.my-config/.p10k.zsh", dest: "~/.p10k.zsh", state: "link", force: yes}
        - {src: "~/.my-config/.usefulCommands.txt", dest: "~/.usefulCommands.txt", state: "link", force: yes}
        - {src: "~/.my-config/.tmux.conf", dest: "~/.tmux.conf", state: "link", force: yes}
        - {src: "~/.my-config/.vimrc", dest: "~/.vimrc", state: "link", force: yes}
        - {src: "~/.my-config/.vim/colors/green_dark.vim", dest: "~/.vim/colors/green_dark.vim", state: "link", force: yes}
        - {src: "~/.my-config/.vim/spell/en.utf-8.add", dest: "~/.vim/spell/en.utf-8.add", state: "link", force: yes}
        - {src: "~/.my-config/.vim/spell/en.utf-8.add.spl", dest: "~/.vim/spell/en.utf-8.add.spl", state: "link", force: yes}
        - {src: "~/.my-config/root/mc/ini", dest: "~/.config/mc/ini", state: "link", force: yes}
        - {src: "~/.my-config/root/mc/panels.ini", dest: "~/.config/mc/panels.ini", state: "link", force: yes}
        - {src: "~/.my-config/htoprc", dest: "~/.config/htop/htoprc", state: "link", force: yes}

#-------------------------- setup ---------------------------------------------------------------
    - name: ROOT SETUP DEFAULT SHELL
      become: yes
      user:
        name: "root"
        shell: /usr/bin/zsh
    - name: ROOT VIM INSTALL PLUGINS
      become: yes
      when: reg_my_config_root.changed
      expect:
        timeout: 60
        echo: yes
        command: vim +PlugInstall +qall
        responses:
          .*(YES|yes).*: "Yes"
          .*ENTER.*: ""
    - name : ROOT AUTO JUMP GREEN
      become: yes
      lineinfile:
        path: /usr/share/autojump/autojump.zsh
        regex: '.*echo -e.*033.*31m'
        line: '                echo -e "\\033[32m${output}\\033[0m"'
        backrefs: yes
    - name: ROOT TMUX AUTO INSTALL PLUGINS
      become: yes
      tags:
        - mytest
      shell: |
        tmux start-server && ~/.tmux/plugins/tpm/scripts/install_plugins.sh
        # cmd: sh 'tmux start-server && tmux new-session -d sleep 1 && ~/.tmux/plugins/tpm/scripts/install_plugins.sh && tmux kill-server'
      register: reg_tmux_auto_isntall_plugins
      when: reg_tmux_auto_isntall_plugins.stdout_lines | regex_search('installed|succesed')
      # failed_when: reg_tmux_auto_isntall_plugins 
    - debug:
        var: reg_tmux_auto_isntall_plugins.stdout_lines
      tags:
        - mytest



#========================== ba666 ===============================================================
#-------------------------- setup ---------------------------------------------------------------
    - name: BQ666 SETUP DEFAULT SHELL
      become: yes
      user:
        name: "bq666"
        shell: /usr/bin/zsh
#-------------------------- git -----------------------------------------------------------------




