---
- hosts: ALL
  user: 'bq666'
  roles:
    - CMD_APT_UPDATE_UPGRADE
    - CMD_INSTALL_DEV
    - CMD_INSTALL_CONSOLE
    - CMD_INSTALL_HARDWARE
    - CMD_INSTALL_NET
    - CMD_INSTALL_HACK
    - CMD_ROOT_MY_CONFIG_GLOBAL
    - CMD_BQ666_MY_CONFIG
