---
- hosts: OLD
  user: 'bq666'
  roles:
    - TEST_PING
    # - CMD_UFW_CLIENT
    # - CMD_APT_UPDATE_UPGRADE
    # - CMD_INSTALL
    # - CMD_GIT
    # - CMD_DOWNLOAD_CONFIGS
    # - CMD_ZSH
    # - CMD_TMUX
    # - CMD_VIM
    # - CMD_MC
    # - CMD_RANGER
    # - CMD_HTOP
    # - CMD_LM_SENSORS
    # - CMD_NVME_CLI
    # - CMD_AUTOJUMP
    # == BIG =====================================================
    # - CMD_BIG
    # - CMD_APC

    # == SERVER =====================================================
    # - CMD_UFW_SERVER



    # - KDE_SETUP
    # - KDE_PROGRAMS
    # - KDE_TILIX
    # - KDE_LIBREOFFICE
    # - KDE_QBITTORRENT
    # - KDE_CONKY_LEN
    # - KDE_CONKY_BIG
    # - KDE_INSTALL
    - KDE_CHROME
    # - KDE_SOLAAR
    # - KDE_OPENRAZER
    # - KDE_WIRESHARK
    # - KDE_QEMU



    # - CMD_INSTALL_HARDWARE
    # - CMD_INSTALL_NET
    #
    # - CMD_ROOT_MY_CONFIG_GLOBAL
    # - CMD_BQ666_MY_CONFIG
    # - role: CMD_WGAUDNIK_MY_CONFIG
      # remote_user: 'wgaudnik'
    # - UFW_CLIENT
    # - UFW_SERVER
    # - CMD_ONLY_BIG
