---
- name: PIP VIM-VINT INSTALL
  become: 'yes'
  pip:
   name: 'vim-vint'
   state: latest

- name: VIVM INSTALL
  become: 'yes'
  get_url:
    url: 'https://raw.githubusercontent.com/thameera/vimv/master/vimv'
    dest: /usr/local/bin/vimv
    mode: '0755'

- name: PIP INSTALL
  become: 'yes'
  pip:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'black'}
    - {source: 'isort'}
    - {source: 'flake8'}
    - {source: 'bandit'}
