- name: APT INSTALL
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'nvme-cli'}
    - {source: 'iftop'}
    - {source: 'hwinfo'}
    - {source: 'smem'}
    - {source: 'glances'}
    - {source: 'iotop'}
    - {source: 'powertop'}
    - {source: 'sysbench'}
    - {source: 'inxi'}
    - {source: 'stress'}
    - {source: 'stress-ng'}
    - {source: 'glmark2'}
- name: ADDITIONAL
  import_tasks: additionals.yml
