- name: APT UPDATE AND UPGRADE
  apt:
    update_cache: 'yes'
    upgrade: 'yes'
    force_apt_get: 'yes'
    cache_valid_time: 3600
    autoremove: 'yes'
- name: APT INSTALL
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'tilix'}
    - {source: 'dconf-cli'}
