- name: LINK FILES
  become: 'yes'
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
    mode='{{ item.mode }}'
  with_items:
    - {src: '~/.my-config/CMD/config/etc/udev/rules.d/70-persistent-net.rules', dest: '/etc/udev/rules.d', state: 'link', force: 'yes', mode: '0700'}
