- name: LINK ADDITIONAL FILES
  file:
    src='{{ item.src }}'
    dest='{{ item.dest }}'
    state='{{ item.state }}'
    force='{{ item.force }}'
  with_items:
    - {src: '~/.my-config/CMD/bq666/mc/ini', dest: '~/.config/mc/ini', state: 'link', force: yes}
    - {src: '~/.my-config/CMD/bq666/mc/panels.ini', dest: '~/.config/mc/panels.ini', state: 'link', force: yes}
