---
- name: APT AUTO JUMP
  become: 'yes'
  apt:
    name: 'autojump'
    state: latest

- name : AUTO JUMP GREEN
  become: 'yes'
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - {path: '/usr/share/autojump/autojump.zsh', regexp: '31', replace: '32'}
    - {path: '/usr/share/autojump/autojump.bash', regexp: '31', replace: '32'}
