- name: APT UPDATE AND UPGRADE
  apt:
    update_cache: 'yes'
    upgrade: 'yes'
    force_apt_get: 'yes'
    cache_valid_time: 3600
    autoremove: 'yes'
- name: APT INSTALL
  apt:
    name: "{{ item.source }}"
    state: latest
  with_items:
    - {source: 'git'}
    - {source: 'zsh'}
    - {source: 'wget'}
    - {source: 'curl'}
    - {source: 'thefuck'}
    - {source: 'autojump'}
    - {source: 'tmux'}
    - {source: 'screenfetch'}
    - {source: 'mc'}
    - {source: 'htop'}
    - {source: 'ripgrep'}
    - {source: 'xsel'}
    - {source: 'xclip'}
    - {source: 'cryptsetup'}
- name: APT VIM INSTALL
  apt:
    name: 'vim'
    state: latest
  register: reg_vim_install
- name: APT LM_SENSORS INSTALL
  apt:
    name: 'lm-sensors'
    state: latest
  register: reg_lm_sensors_install
- name: PIP VIM-VINT INSTALL
  pip:
   name: 'vim-vint'
   state: latest
- name: GEM COLORLS INSTALL
  gem:
    name: 'colorls'
    user_install: no
    state: latest
- name: VIVM INSTALL
  get_url:
    url: 'https://raw.githubusercontent.com/thameera/vimv/master/vimv'
    dest: /usr/local/bin/vimv
    mode: '0755'
