- name: LM_SENSORS DETECT
  become: 'yes'
  expect:
    timeout: 60
    echo: yes
    command: '/sbin/sensors-detect'
    responses:
      'Do you want to add these lines automatically to /etc/modules? (yes/NO)': 'yes'
      '.*(YES/no).*': 'YES'
      '.*(yes/NO).*': 'NO'
      '(YES/no/selectively)': 'YES'
      '(yes/NO/selectively)': 'NO'
      '.*ENTER.*': ''
