- name: APT INSTALL
  become: 'yes'
  apt:
    name: '{{ item.source }}'
    state: latest
  with_items:
    - {source: 'iftop'}
    - {source: 'hwinfo'}
    - {source: 'smem'}
    - {source: 'glances'}
    - {source: 'iotop'}
    - {source: 'powertop'}
    - {source: 'sysbench'}
    - {source: 'inxi'}
    - {source: 'stress'}
    - {source: 'stress-ng'}
    - {source: 'glmark2'}
- name: NVME-CLI APT INSTALL
  become: 'yes'
  apt:
    name: 'nvme-cli'
    state: latest
  register: reg_nvme_cli_install
- name: LM_SENSORS APT INSTALL
  become: 'yes'
  apt:
    name: 'lm-sensors'
    state: latest
  register: reg_lm_sensors_install

- name: NVME-CLI SET SUID
  when: reg_nvme_cli_install.changed
  import_tasks: nvme_cli_set_suid.yml
- name: LM SENSORS DETECT
  when: reg_lm_sensors_install.changed
  import_tasks: lm_sensors_detect.yml
