- name: TEST HOSTS
  become: 'yes'
  shell: 'cat /etc/hosts'
  register: reg_test_hosts
  changed_when: false
- name: ADD HOSTS
  become: 'yes'
  lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
    insertbefore: '{{ item.insertbefore }}'
  with_items:
    - {path: '/etc/hosts', line: ' ', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '#eth', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.1     GAT', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.107   TVS', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.114   BIG', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.202   OLD', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.229   NAS nextCloud mypage plex', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: ' ', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '#wifi', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.31    SG8', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.11    RN8', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.116   LEN', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.132   MTO', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.236   HPD', insertbefore: 'EOF'}
    - {path: '/etc/hosts', line: '192.168.0.237   YOG', insertbefore: 'EOF'}
  when: reg_test_hosts.stdout.find('TVS') == -1
- name: RESTART SYSTEM-RESOLVED.SERVICE
  become: 'yes'
  systemd:
    name: 'systemd-resolved'
    state: restarted
  changed_when: false
