---
- name: NVME-CLI APT INSTALL
  become: 'yes'
  apt:
    name: 'nvme-cli'
    state: latest
  register: reg_nvme_cli_install
- name: NVME-CLI SET SUID
  become: 'yes'
  when: reg_nvme_cli_install.changed
  file:
    path: '{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - {path: '/usr/sbin/nvme', mode: '4555'}
